// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProviderFilterController from "./provider_filter_controller"
application.register("provider-filter", ProviderFilterController)

import PurgeController from "./purge_controller"
application.register("purge", PurgeController)
