development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: redis://default:b5444d475c35ca801ee6668c@10.114.0.2:6379/0
  channel_prefix: wedding_production
